## YAML Template.
---
version: 0.0
os: linux

files:
  - source: ./home/circleci/project/target/ROOT.war
    destination: /var/lib/tomcat9/webapps
  - source: ./cloudwatch.json
    destination: /opt/aws/amazon-cloudwatch-agent/bin
    
hooks:
    ApplicationStop:
    - location: ./codedeploy/applicationStop.sh    
      timeout: 120
      runas: ubuntu
    BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh    
      timeout: 120
      runas: ubuntu
    AfterInstall:
    - location: ./codedeploy/afterInstall.sh    
      timeout: 120
      runas: ubuntu
    ApplicationStart:
    - location: ./codedeploy/applicationStart.sh    
      timeout: 120
      runas: ubuntu
    - location: ./codedeploy/validateService.sh    
      timeout: 120
      runas: ubuntu